### ISSUE TITLE
assets doesn't exist

### ISSUE THREAD

**Issue by wangjiawen2013** [databio/pepatac#175]
Hi,
I ran pepatac directly following the tutorial: http://pepatac.databio.org/en/latest/run-directly/
But it didn't work, the process stopped and showed that :
 pepatac.py --single-or-paired paired --prealignments human_repeats --genome hg38 --sample-name test1 --input ~/bin/pepatac/examples/data/test1_r1.fastq.gz ~/bin/pepatac/examples/data/test1_r2.fastq.gz --genome-size hs -O ./test1
Removed existing flag: '/home/wangjw/data/work/atacseq/test1/test1/test1/test1/PEPATAC_failed.flag'
### Pipeline run code and environment:

*              Command:  `/home/wangjw/bin/pepatac/pipelines/pepatac.py --single-or-paired paired --prealignments human_repeats --genome hg38 --sample-name test1 --input /home/wangjw/bin/pepatac/examples/data/test1_r1.fastq.gz /home/wangjw/bin/pepatac/examples/data/test1_r2.fastq.gz --genome-size hs -O ./test1`
*         Compute host:  Gilbert2
*          Working dir:  /home/wangjw/data/work/atacseq/test1/test1
*            Outfolder:  /home/wangjw/data/work/atacseq/test1/test1/test1/test1/
*  Pipeline started at:   (03-29 15:12:22) elapsed: 0.0 _TIME_

### Version log:

*       Python version:  3.8.8
*          Pypiper dir:  `/home/wangjw/bin/miniconda3/envs/pepatac/lib/python3.8/site-packages/pypiper`
*      Pypiper version:  0.12.1
*         Pipeline dir:  `/home/wangjw/bin/pepatac/pipelines`
*     Pipeline version:  0.9.15
*        Pipeline hash:  acb762dbb453e94d4820e9dd9624dfbcf03472ef
*      Pipeline branch:  * master
*        Pipeline date:  2021-03-25 08:18:10 -0400

### Arguments passed to pipeline:

*           `TSS_name`:  `None`
*            `aligner`:  `bowtie2`
*          `anno_name`:  `None`
*          `blacklist`:  `None`
*        `config_file`:  `pepatac.yaml`
*              `cores`:  `1`
*       `deduplicator`:  `samblaster`
*              `dirty`:  `False`
*             `extend`:  `250`
*       `force_follow`:  `False`
*     `frip_ref_peaks`:  `None`
*    `genome_assembly`:  `hg38`
*        `genome_size`:  `hs`
*              `input`:  `['/home/wangjw/bin/pepatac/examples/data/test1_r1.fastq.gz', '/home/wangjw/bin/pepatac/examples/data/test1_r2.fastq.gz']`
*             `input2`:  `None`
*               `keep`:  `False`
*               `lite`:  `False`
*             `logdev`:  `False`
*                `mem`:  `4000`
*              `motif`:  `False`
*          `new_start`:  `False`
*            `no_fifo`:  `False`
*           `no_scale`:  `False`
*      `output_parent`:  `./test1`
*         `paired_end`:  `True`
*        `peak_caller`:  `macs2`
*          `peak_type`:  `fixed`
*      `prealignments`:  `['human_repeats']`
*         `prioritize`:  `False`
*            `recover`:  `False`
*        `sample_name`:  `test1`
*             `silent`:  `False`
*   `single_or_paired`:  `paired`
*             `skipqc`:  `False`
*                `sob`:  `False`
*           `testmode`:  `False`
*            `trimmer`:  `skewer`
*          `verbosity`:  `None`

----------------------------------------

/home/wangjw/bin/miniconda3/envs/pepatac/lib/python3.8/site-packages/refgenconf/refgenconf.py:752: RuntimeWarning: For genome 'human_repeats' alias to the asset 'bowtie2_index/None:default' doesn't exist: /home/wangjw/data/references/ATACseq/alias/human_repeats/bowtie2_index/default/human_repeats
  warnings.warn(msg, RuntimeWarning)
/home/wangjw/bin/miniconda3/envs/pepatac/lib/python3.8/site-packages/refgenconf/refgenconf.py:752: RuntimeWarning: For genome 'hg38' alias to the asset 'bowtie2_index/bowtie2_index:default' doesn't exist: /home/wangjw/data/references/ATACseq/alias/hg38/bowtie2_index/default/hg38
  warnings.warn(msg, RuntimeWarning)
Some assets are not found. You can update your REFGENIE config file or point directly to the file using the noted command-line arguments:
Optional assets not existing: blacklist.blacklist:default (--blacklist)
Local input file: /home/wangjw/bin/pepatac/examples/data/test1_r1.fastq.gz

> `File_mb`	1	2	_RES_

> `Read_type`	paired	PEPATAC	_RES_

> `Genome`	hg38	PEPATAC	_RES_

### Merge/link and fastq conversion:  (03-29 15:12:23) elapsed: 0.0 _TIME_

Number of input file sets: 1
Target exists: `/home/wangjw/data/work/atacseq/test1/test1/test1/test1/raw/test1.merged.fastq.gz`  
Local input file: '/home/wangjw/data/work/atacseq/test1/test1/test1/test1/raw/test1.merged.fastq.gz'
Found .fastq.gz file
Traceback (most recent call last):
  File "/home/wangjw/bin/pepatac/pipelines/pepatac.py", line 2731, in <module>
    sys.exit(main())
  File "/home/wangjw/bin/pepatac/pipelines/pepatac.py", line 771, in main
    cmd, out_fastq_pre, unaligned_fastq = ngstk.input_to_fastq(
  File "/home/wangjw/bin/miniconda3/envs/pepatac/lib/python3.8/site-packages/pypiper/ngstk.py", line 458, in input_to_fastq
    raise NotImplementedError("Can't use zipmode on interleaved fastq data.")
NotImplementedError: Can't use zipmode on interleaved fastq data.

### Pipeline failed at:  (03-29 15:12:23) elapsed: 0.0 _TIME_

Total time: 0:00:00
Failure reason: Pipeline failure. See details above.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/wangjw/bin/miniconda3/envs/pepatac/lib/python3.8/site-packages/pypiper/manager.py", line 1799, in _exit_handler
    self.fail_pipeline(Exception("Pipeline failure. See details above."))
  File "/home/wangjw/bin/miniconda3/envs/pepatac/lib/python3.8/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
Exception: Pipeline failure. See details above.

**Comment by wangjiawen2013** [comment]
I didn't get any results, who can helps?

**Comment by jpsmith5** [comment]
So, the asset message is a reflection of some runtime warnings from Refgenie. Those, being warnings, can be safely disregarded here, and we're in the process of releasing some new updates to Refgenie itself that will then allow us to address these superfluous warnings.  It looks like the real error here is that it is seeing the test file as an interleaved fastq file:
```
File "/home/wangjw/bin/miniconda3/envs/pepatac/lib/python3.8/site-packages/pypiper/ngstk.py", line 458, in input_to_fastq
raise NotImplementedError("Can't use zipmode on interleaved fastq data.")
```
Which is strange and a new error for me. I just successfully ran the `run-direct` command from within the `pepatac/` directory like so:
```
 pipelines/pepatac.py --single-or-paired paired   --prealignments rCRSd human_repeats   --genome hg38   --sample-name test1   --input examples/data/test1_r1.fastq.gz   --input2 examples/data/test1_r2.fastq.gz   --genome-size hs   -O $HOME/pepatac_test
```

It looks like you're using the included test sample, so I'm not sure yet what is happening for that error to appear. I'll keep testing on my side and see if I can replicate your error.

**Comment by wangjiawen2013** [comment]
I ran it successfully within the pepatac/ directory now, then I ran it successully in my customized directory too! I don't know why. it it possible that it must be ran within pepatac installation directory first, the first run perhaps adapted some configuration ?

**Comment by jpsmith5** [comment]
Yeah, all I can imagine is something about it running in multiple subdirectories named `test` was somehow causing a conflict. I noticed it looked like each time you were attempting to run the test it was creating more and more `/test/` directories. But that's just conjecture.  I'll see if I can do something similar on my side and replicate the error, and then hopefully we can stop that happening to anyone else in the future. Glad to know you got it running. Let me know how I else I can help.

**Comment by wangjiawen2013** [comment]
I also can run pepatac using looper now ! Pepatac is a cutting edge atacseq pipeline, there are so many configuration files that I must spend some time being faimliar with it. If I wanna call peaks with HMMRATAC and change some parameters (for example, the p-value threshold of MCS2), how should I modify the config file ?

**Comment by jpsmith5** [comment]
## Using HMMRATAC

For changing the peak caller, you can specify `hmmratac` as the peak caller. Here's and example with the test data.  In my example configuration file I've preset some environment variables to make it more portable. So, PROCESSED is an environment variable that is pointing to my parent output folder where I want to store results.  CODE points to the parent directory containing my various tools and coding work. You could specify full paths here or do something similar.

```
name: test_project # The name that summary files will be prefaced with

pep_version: 2.0.0
sample_table: test_annotation.csv  # sheet listing all samples in the project

looper:  # relative paths are relative to this config file
  output_dir: "$PROCESSED/pepatac/test/hmmratac"  
  pipeline_interfaces: ["$CODE/pepatac/project_pipeline_interface.yaml"] 

sample_modifiers:
  append:
    pipeline_interfaces: ["$CODE/pepatac/sample_pipeline_interface.yaml"]
  derive:
    attributes: [read1, read2]
    sources:
      test_data_R1: "$CODE/pepatac/examples/data/{sample_name}_r1.fastq.gz"
      test_data_R2: "$CODE/pepatac/examples/data/{sample_name}_r2.fastq.gz"
  imply:
    - if: 
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then: 
        genome: hg38
        macs_genome_size: hs
        prealignments: rCRSd
        peak_caller: hmmratac
```

You would also have needed to specify a path to the HMMRATAC java file in the [`pepatac.yaml` configuration file](https://github.com/databio/pepatac/blob/master/pipelines/pepatac.yaml).   Specifically this line in that file:
```
hmmratac: ${HMMRATAC}
```
So you could have an environment variable like so: `export HMMRATAC="/home/$USER/.local/bin/HMMRATAC_V1.2.10_exe.jar"`

## Changing MACS2 p-value

In the same [`pepatac.yaml` configuration file](https://github.com/databio/pepatac/blob/master/pipelines/pepatac.yaml) we just were referencing, you can also adjust MACS2 parameters. Under the `parameters` subsection you'll see the following lines:
```
  macs2:
    params: '--shift -75 --extsize 150 --nomodel --call-summits --nolambda --keep-dup all -p 0.01'
    # -f: Format of tag file.
    # -q: The qvalue (minimum FDR) cutoff to call significant regions.
    # --shift:  Assign an arbitrary shift in bp. See MACS documentation.
    # --nomodel: Will bybass building the shifting model.
```
So you could just change the `-p` parameter value right there to adjust.

## Cores

Generally speaking, where a tool can utilize multiple cores, it already is designed to do so based on what you've passed to the system.  The pipeline framework in which `pepatac` is written already includes a `-P` or `--cores` argument. And this value with looper is intelligently chosen based on the included [`resources-sample.tsv` file](https://github.com/databio/pepatac/blob/master/resources-sample.tsv). But you could specify at the command-line with that `-P` argument.

**Comment by wangjiawen2013** [comment]
Is it better to replace "macs_genome_size" with "genome_size" ? macs_genome_size is a bit confusing, especially when using other peak callers (such as HMMRATAC, not macs2).  It looks like we are still using macs if using macs_genome_size. By the way, do these parameters "genome, macs_genome_size, prealignments, peak_caller" correspond to that of pipelines/pepatac.py ?

**Comment by wangjiawen2013** [comment]
I tried it following your instruction, while it looks like pepatac still uses mcas2:
(pepatac) [wangjw@Gilbert2 atacseq]$ cat processed/results_pipeline/tutorial1/PEPATAC_log.md
### Pipeline run code and environment:

*              Command:  `/home/wangjw/bin/pepatac/pipelines/pepatac.py --sample-name tutorial1 --genome hg38 --input /home/wangjw/data/work/atacseq/data/tutorial1_r1.fastq.gz --single-or-paired paired -O /home/wangjw/data/work/atacseq/processed/results_pipeline -P 4 -M 8000 --input2 /home/wangjw/data/work/atacseq/data/tutorial1_r2.fastq.gz --peak-caller hmmratac --genome-size hs --prealignments rCRSd human_repeats`
*         Compute host:  Gilbert2
*          Working dir:  /home/wangjw/bin/pepatac
*            Outfolder:  /home/wangjw/data/work/atacseq/processed/results_pipeline/tutorial1/
*  Pipeline started at:   (04-02 09:08:21) elapsed: 0.0 _TIME_

### Version log:

*       Python version:  3.8.8
*          Pypiper dir:  `/home/wangjw/bin/miniconda3/envs/pepatac/lib/python3.8/site-packages/pypiper`
*      Pypiper version:  0.12.1
*         Pipeline dir:  `/home/wangjw/bin/pepatac/pipelines`
*     Pipeline version:  0.9.15
*        Pipeline hash:  acb762dbb453e94d4820e9dd9624dfbcf03472ef
*      Pipeline branch:  * master
*        Pipeline date:  2021-03-25 08:18:10 -0400

### Arguments passed to pipeline:

*           `TSS_name`:  `None`
*            `aligner`:  `bowtie2`
*          `anno_name`:  `None`
*          `blacklist`:  `None`
*        `config_file`:  `pepatac.yaml`
*              `cores`:  `4`
*       `deduplicator`:  `samblaster`
*              `dirty`:  `False`
*             `extend`:  `250`
*       `force_follow`:  `False`
*     `frip_ref_peaks`:  `None`
*    `genome_assembly`:  `hg38`
*        `genome_size`:  `hs`
*              `input`:  `['/home/wangjw/data/work/atacseq/data/tutorial1_r1.fastq.gz']`
*             `input2`:  `['/home/wangjw/data/work/atacseq/data/tutorial1_r2.fastq.gz']`
*               `keep`:  `False`
*               `lite`:  `False`
*             `logdev`:  `False`
*                `mem`:  `8000`
*              `motif`:  `False`
*          `new_start`:  `False`
*            `no_fifo`:  `False`
*           `no_scale`:  `False`
*      `output_parent`:  `/home/wangjw/data/work/atacseq/processed/results_pipeline`
*         `paired_end`:  `True`
*        `peak_caller`:  `hmmratac`
*          `peak_type`:  `fixed`
*      `prealignments`:  `['rCRSd', 'human_repeats']`
*         `prioritize`:  `False`
*            `recover`:  `False`
*        `sample_name`:  `tutorial1`
*             `silent`:  `False`
*   `single_or_paired`:  `paired`
*             `skipqc`:  `False`
*                `sob`:  `False`
*           `testmode`:  `False`
*            `trimmer`:  `skewer`
*          `verbosity`:  `None`

----------------------------------------


### Pipeline failed at:  (04-02 09:08:21) elapsed: 0.0 _TIME_

Total time: 0:00:00
Failure reason: Must use MACS2 with `--peak-type fixed` width peaks. Either change the `--peak-caller ['fseq', 'genrich', 'hmmratac', 'homer', 'macs2']` or use `--peak-type variable`.
Traceback (most recent call last):
  File "/home/wangjw/bin/pepatac/pipelines/pepatac.py", line 2731, in <module>
    sys.exit(main())
  File "/home/wangjw/bin/pepatac/pipelines/pepatac.py", line 581, in main
    pm.fail_pipeline(RuntimeError(err_msg))
  File "/home/wangjw/bin/miniconda3/envs/pepatac/lib/python3.8/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
RuntimeError: Must use MACS2 with `--peak-type fixed` width peaks. Either change the `--peak-caller ['fseq', 'genrich', 'hmmratac', 'homer', 'macs2']` or use `--peak-type variable`.

**Comment by jpsmith5** [comment]
> Is it better to replace "macs_genome_size" with "genome_size" ? macs_genome_size is a bit confusing, especially when using other peak callers (such as HMMRATAC, not macs2). It looks like we are still using macs if using macs_genome_size. By the way, do these parameters "genome, macs_genome_size, prealignments, peak_caller" correspond to that of pipelines/pepatac.py ?

Oh yes, sorry that's a good catch, it should be just `genome_size` not `macs_genome_size`. 

So, it is using `hmmratac`, see the line: ``peak_caller`:  `hmmratac``

And it's saying, to use hmmratac, you must also specify to use the `--peak-type variable` parameter. And yes I'm sorry I forgot to include that in my example.  It's just saying that if you specify fixed width peaks it's expecting you to use MACS, otherwise you need to specify variable.  So, to modify the earlier example:
```
name: test_project # The name that summary files will be prefaced with

pep_version: 2.0.0
sample_table: test_annotation.csv  # sheet listing all samples in the project

looper:  # relative paths are relative to this config file
  output_dir: "$PROCESSED/pepatac/test/hmmratac"  
  pipeline_interfaces: ["$CODE/pepatac/project_pipeline_interface.yaml"] 

sample_modifiers:
  append:
    pipeline_interfaces: ["$CODE/pepatac/sample_pipeline_interface.yaml"]
  derive:
    attributes: [read1, read2]
    sources:
      test_data_R1: "$CODE/pepatac/examples/data/{sample_name}_r1.fastq.gz"
      test_data_R2: "$CODE/pepatac/examples/data/{sample_name}_r2.fastq.gz"
  imply:
    - if: 
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then: 
        genome: hg38
        genome_size: hs
        prealignments: rCRSd
        peak_caller: hmmratac
        peak_type: variable
```

Sorry about that, I simply forgot to include the `peak_type` line in the example I shared.
