### ISSUE TITLE
Specifying genome size in config.yaml

### ISSUE THREAD

**Issue by gbloeb** [databio/pepatac#214]
I have tried passing the genome size to pepatac through parameter in the config.yaml  file unsuccessfully.

```
imply:
    - if:
	organism: ["mouse"]
      then:
	genome: mm10
        prealignment_names: ["mouse_chrM2x"]
        genome-size: 2.3e9
```

and 

```
imply:
    - if:
	organism: ["mouse"]
      then:
	genome: mm10
        prealignment_names: ["mouse_chrM2x"]
        macs_genome_size: 2.3e9
```

In my submission scripts still get:
--genome-size "2.7e9"
