### ISSUE TITLE
What do the sequence names in the default adapter file NexteraPE-PE.fa mean? Does the default adapter file work for most ATACseq experiments? How to set my own adapter file?

### ISSUE THREAD

**Issue by yqlan** [databio/pepatac#252]

**Comment by jpsmith5** [comment]
Added a "Using a custom adapter file" subsection to `docs/assets.md` on `dev`. Short version: set the `adapters` resource in `pipelines/pepatac.yaml`:

```yaml
resources:
  genome_config: ${REFGENIE}
  adapters: /path/to/your/adapters.fa
```

The file must be in FASTA format (consumed by `trimmomatic`'s `ILLUMINACLIP` and `skewer`'s `-x`). Setting `adapters: null` falls back to the bundled NexteraPE-PE.fa. Ships in upcoming v0.14.0. Closing.
